### ISSUE TITLE
Cannot read property 'firstElementChild' of null

### ISSUE THREAD

**Issue by vikramTungsten** [legalthings/pdf.js-viewer#23]
I am trying to embedded pdf on my html page using pdf.js, with the help of pdf [viewer blog](https://www.npmjs.com/package/pdf.js-viewer),I have included pdf.js and pdf.worker.js in my html file, but when I open the page, nothing is embedded and I am getting below error.
`Cannot read property firstElementChild of null`

Please help me in this.
Thanks!

HTML Code:
```
<body>  
<div class="pdfjs">
</div> 
<script src="{% static 'pdf.js-viewer/pdf.js'%}"></script>
<script src="{% static 'pdf.js-viewer/pdf.worker.js'%}"></script> 

<script type="text/javascript">
      PDFJS.webViewerLoad('http://url/mypdf.pdf');
</script>
</body>
```

Checkout below error:

Uncaught (in promise) TypeError: Cannot read property 'firstElementChild' of null at Object.PDFViewer (http://url/pdf.js:17939:52) at http://url/pdf.js:12985:21 at Object._initializeViewerComponents (http://url/pdf.js:12973:10) at http://url/pdf.js:12884:16PDFViewer

**Comment by pierregaboriaud** [comment]
Any news ?

**Comment by brandonros** [comment]
https://github.com/legalthings/angular-pdfjs-viewer/issues/65

**Comment by micheg** [comment]
<html>
  <head>
    <title>PDF.js viewer</title>
    <script src="bower_components/pdf.js-viewer/pdf.js"></script>
    <link rel="stylesheet" href="bower_components/pdf.js-viewer/viewer.css">
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous">
    </script>

    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

  <body>
    <div class="pdfjs">
    </div>

    <script>
      var file = 'some-document.pdf'; 
      // waiting for page load, loading the content of viewer.html inside pdfjs THEN load file
      $(function()
      {
        $('div.pdfjs').load("./viewer.html", function()
        {
          window.PDFJS.webViewerLoad();
          window.PDFViewerApplication.open(file);     
        });
      });
    </script>
  </body>
</html>

**Comment by ArkojeetSuntel** [comment]
`import React, { useEffect, useState } from 'react';
import {
    EventBus,
    PDFViewer,
    PDFLinkService,
    PDFFindController,
  } from "pdfjs-dist/legacy/web/pdf_viewer";

  import type { PDFDocumentProxy } from "pdfjs-dist";
import debounce from 'lodash.debounce';

interface Props{
    pdfDocument: PDFDocumentProxy;
    pdfScaleValue?: string;
}

const PdfHighlighter: React.FC<Props> = ({pdfDocument, pdfScaleValue}: Props) => {
    const [viewer, setViewer] = useState<PDFViewer | null>(null);
    const [containerNode, setContainderNode] = useState<HTMLDivElement | null>(null);
    const [eventBus, setEventBus] = useState<EventBus>(new EventBus());
    const [linkService, setLinkService] = useState<PDFLinkService>(new PDFLinkService({
        eventBus: eventBus,
        externalLinkTarget: 2,
      }));
    const [observer, setObserver] = useState<ResizeObserver | null>(null);
    const [scaleValue, setScaleValue] = useState<string>("auto");

    useEffect(() => {
        setPdfScaleValue();
        if (typeof ResizeObserver !== "undefined"){
            setObserver(new ResizeObserver(debouncedScaleValue));
        };
        init();
    }, []);

    const setPdfScaleValue = () => {
        if(pdfScaleValue){
            setScaleValue(pdfScaleValue);
        }
    }

    const handleScaleValue = () => {
        if (viewer) {
          viewer.currentScaleValue = scaleValue; //"page-width";
        }
      };

    const debouncedScaleValue= () =>{ debounce(handleScaleValue, 500);}

    let unsubscribe = () => {};

    const attachRef = (ref: HTMLDivElement) => {
        setContainderNode(ref);
        unsubscribe();
    
        if (ref) {
          if (observer) observer.observe(ref);
    
          unsubscribe = () => {
            if (observer) observer.disconnect();
          };
        }
      };

    const init = () => {
        setViewer(new PDFViewer({
            container: containerNode!,
            eventBus: eventBus,
            textLayerMode: 2,
            removePageBorders: true,
            linkService: linkService,
            findController: new PDFFindController({
              eventBus: eventBus,
              linkService: linkService,
            }),
            renderer: "canvas",
            l10n: null,
            }))
    
        linkService.setDocument(pdfDocument);
        linkService.setViewer(viewer);
        if(viewer){
            viewer.setDocument(pdfDocument);
        } else {
            console.log("Viewer is null");
        }

        (window as any).PdfViewer = this;
    }

    return (
        <div>
        <div
          ref={attachRef}
          className="PdfHighlighter"
        />
        </div>
    );
}

export default `PdfHighlighter;`



This is my code and I am using this to render a pdf on the html page. But I get this error:

Cannot read properties of null (reading 'firstElementChild')
TypeError: Cannot read properties of null (reading 'firstElementChild')
    at new BaseViewer (http://localhost:3000/static/js/bundle.js:77494:63)
    at PDFViewer._createSuperInternal (http://localhost:3000/static/js/bundle.js:79208:32)
    at new PDFViewer (http://localhost:3000/static/js/bundle.js:79251:27)
    at init (http://localhost:3000/main.77914745b278ba956479.hot-update.js:78:15)
    at http://localhost:3000/main.77914745b278ba956479.hot-update.js:50:5
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:100802:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:102295:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:102267:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:102257:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:102247:7)

Along with this error:
Converting circular structure to JSON
    --> starting at object with constructor 'WorkerTransport'
    |     property 'loadingTask' -> object with constructor 'PDFDocumentLoadingTask'
    --- property '_transport' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'WorkerTransport'
    |     property 'loadingTask' -> object with constructor 'PDFDocumentLoadingTask'
    --- property '_transport' closes the circle
    at JSON.stringify (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:11899:38
    
    
    Can anyone help me to understand why I have this error.
    
    I am using PdfHighlighter as a JS component prop for this compoenent to see if the pdf is loading or not.
    `import React, { Component, useEffect, useState } from "react";

import { getDocument, GlobalWorkerOptions, isPdfFile } from "pdfjs-dist/legacy/build/pdf";
import type { PDFDocumentProxy } from "pdfjs-dist";

interface Props {
  url: string;
  beforeLoad: JSX.Element;
  errorMessage?: JSX.Element;
  children: (pdfDocument: PDFDocumentProxy) => JSX.Element;
  onError?: (error: Error) => void;
  cMapUrl?: string;
  cMapPacked?: boolean;
}

const PdfLoader = ({url, beforeLoad, errorMessage, children, onError, cMapUrl, cMapPacked}:Props) => {

  const [pdfDocument, setPdfDocument] = useState<PDFDocumentProxy | null>(null);
  const [error, setError] = useState<Error|null>(null);
  
  const workerSrc:string =  "https://unpkg.com/pdfjs-dist@2.11.338/build/pdf.worker.min.js";

  const documentRef = React.createRef<HTMLElement>();

  useEffect(() => {
    load();
    return () => {
      console.log('my effect is destroying');
      const discardedDocument = pdfDocument;
      if(discardedDocument){
        discardedDocument.destroy();
      }
    };
  }, [url])

  const componentDidCatch = (error: Error, info?: any) => {
    if (onError) {
      onError(error);
    }

    console.log("Caught Error while loading");

    setPdfDocument(null);
    setError(error);
  }

  const load = () => {
    const { ownerDocument = document } = documentRef.current || {};
    const discardedDocument = pdfDocument;

    if (typeof workerSrc === "string") {
      GlobalWorkerOptions.workerSrc = workerSrc;
    }

    Promise.resolve()
      .then(() => discardedDocument && discardedDocument.destroy())
      .then(() => {
        if (!url) {
          return;
        }

        return getDocument({
          url,
          ownerDocument,
          cMapUrl,
          cMapPacked,
        }).promise.then((pdfDocument) => {
          setPdfDocument(pdfDocument);
        });
      })
      .catch((e) => componentDidCatch(e));
  }

const renderError = () => {
    if (errorMessage) {
      return React.cloneElement(errorMessage, {error: error});
    }

    return null;
  }
    return (
      <>
        <span ref={documentRef} />
        {error
          ? renderError()
          : !pdfDocument || !children
          ? beforeLoad
          : children(pdfDocument)}
      </>
    );

  
}

export default PdfLoader;
`

This is my first time asking a question so if anyway I can improve my query, please do tell me what to do.
