### ISSUE TITLE
New version of PDF.js

### ISSUE THREAD

**Issue by kplogo** [legalthings/pdf.js-viewer#9]
Hi.
Is there any chance, that You will upgrade pdf.js-viewer to the latest version of PDF.js? I looked at Your instruction, and noticed that it isn't actual, so I can't do that myself.

As far as I know in new version ar a lot of bug fixes, so it will be very helpful ;)

Thanks
Kplogo

**Comment by jasny** [comment]
@kplogo Eventually, but it's not on our shortlist. I would really like a PR for this.
